### ISSUE TITLE
AppIdleWarn Suggestion..

### ISSUE THREAD

**Issue by ijbranch** [corneliusdavid/ccLib#1]
I changed AppIdleWarn per the attached file to show the Application's filename in the warning dialog
[AppIdleWarn.zip](https://github.com/corneliusdavid/ccLib/files/9070291/AppIdleWarn.zip)
.Hope this is of some value.

Also, AppIdleWarn had {$IFDEF XEorHIGHER} at the start of the uses.  Should be {$IFDEF XE2orHIGHER}.

Regards,
Ian

**Comment by corneliusdavid** [comment]
Thanks for the contribution! I added `ShowAppName` a checkbox option in the component.
