### ISSUE TITLE
Building in D12.1 issue.

### ISSUE THREAD

**Issue by ijbranch** [corneliusdavid/ccLib#3]
I have downloaded the latest ccLib from GitHub.
When I try to build ccLib in D12.1 I get this error message:
[dcc64 Error] uConfigIniPersist.pas(460): E2010 Incompatible types: 'TGetCfgValueFunction' and 'Procedure'

Regards,
Ian

**Comment by corneliusdavid** [comment]
Wow, how did that get into the repository? It looks like I was either half asleep or only half done and had not tested or even tried to compile. I'm working through the code and remembering what I was in the process of doing and should have an update in a couple of days. Thanks for pointing this glaring error out to me!  LOL!

**Comment by ijbranch** [comment]
No problem.

**Comment by corneliusdavid** [comment]
OK, I've added a couple of commits and it now compiles. The `TIniPersist` class works with INI files but the new part that works with strings is not. I've restructured the classes (again) and will get this working in the next few days.

**Comment by ijbranch** [comment]
Hi David,
              I just downloaded and tried it.  Not good.
              When it tries to build cclib_D290 it tells me:
              >>[dcc32 Fatal Error] ccLib_R.dpk(31): E2225 Never-build package 'rtl' must be recompiled
              But cclib_r290 built OK.
              It also says:
              >>[dcc32 Fatal Error] ccLib_D.dpk(37): E2202 Required package 'ccLib_R' not found
              But cclib_R290 built OK.

**Comment by ijbranch** [comment]
Hi David,
              Found it.  Cclib_r290 was set to Windows 64-bit while cclib_d290 was set to 32-bit.
              Resetting cclib_r290 to 32-bit fixed it.
              It builds & installs.

**Comment by corneliusdavid** [comment]
Fixed a bug and set all projects in D11/D12 to 32-bit for consistency. Should all be clean and working now! :-) Thanks for reporting!

**Comment by ijbranch** [comment]
Noted.  Tks.
