### ISSUE TITLE
Issues in ltest release...

### ISSUE THREAD

**Issue by ijbranch** [corneliusdavid/ccLib#4]
In CloseApplicationReg::
{ TCloseAppComponent }

procedure TCloseAppComponent.ExecuteVerb(Index: Integer);
{$IFDEF VER130} <<<<<
const <<<<<<
sLineBreak = https://github.com/cclib/cclib/issues/13#10;
{$ENDIF}
begin
case Index of

In AppIdleWarn:
{$I cc.inc}

uses
{$IFDEF XE2orHIGHER}
Winapi.Windows, Winapi.Messages, System.SysUtils, System.Variants, System.Classes, Vcl.Graphics, System.IOUtils,
Vcl.Controls, Vcl.Forms, Vcl.Dialogs, Vcl.Buttons, Vcl.StdCtrls, VCL.ExtCtrls <<<<<<<<<
{$ELSE}
Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs, {$IFNDEF VER130} IOUtils, {$ENDIF}
StdCtrls, Buttons, ExtCtrls
{$ENDIF}
; <<<<<<<<<<
type

**Comment by corneliusdavid** [comment]
Thanks--compiled with D5 on one machine, checked it all in but had not compiled in D12 on a different one. Both corrections submitted.

**Comment by ijbranch** [comment]
Hi Corneliusdavid/cclib,
😊

Regards,
Ian
The Programmer’s Credo:  We do these things not because they are easy, but because we thought they were going to be easy… ***@***.*** - 05/08/2016)
